### ISSUE TITLE
unexpected output

### ISSUE THREAD

**Issue by naveranoc** [sentiment-analysis-spanish/sentiment-spanish#3]
Hi, I again XD

I am doing experiments with the library, and I am getting unexpected results, for example:

print(sentiment.sentiment("hoy estoy feliz"))
0.42223328
print(sentiment.sentiment("hoy no estoy feliz"))
0.42223328
print(sentiment.sentiment("hoy no estoy triste"))
0.000609158
print(sentiment.sentiment("hoy estoy triste"))
0.000609158

Do you think is something about the training data? Something can me help you?

Thanks in advance

**Comment by HugoJBello** [comment]
Hi, the library gets a bit confused with short sentences, It is better to feed it larger sentences or paragraphs. The neural network model currently sees words one by one and does not have into account tuples.  I am working on improving the model to catch that.

**Comment by tommantonela** [comment]
Hi! When I run the example in the readme:
```
sentiment = sentiment_analysis.SentimentAnalysisSpanish()
print(sentiment.sentiment("me gusta la tombola es genial"))
```
instead of 1 y get 0.66. When I check the first model it was uploaded to the repo I get the expected results. Besides the differences in the architecture of the models, was there any difference on the training data?

Thanks!

**Comment by HugoJBello** [comment]
hi @tommantonela , In the last version these problems are fixed. I updated the model, not it works without tensorfow and works with Navie Bayes (sckitlearn) instead. The code you show will get you 0.93 now.

Now the model uses n-grams so it will recognize negations and so on. For Instance if you try

`sentiment = sentiment_analysis.SentimentAnalysisSpanish()

print(sentiment.sentiment("no me gusta la tombola"))
`
you will get 0.0328

**Comment by HugoJBello** [comment]
@naveranoc The last version fixes this problem

```
print(sentiment.sentiment("hoy no estoy feliz"))
print(sentiment.sentiment("hoy no estoy triste"))
print(sentiment.sentiment("hoy estoy triste"))
```

will give you

0.009662391103846214
0.0003260657892194857
0.0030232047083950434

although it does not recognize "hoy no estoy triste" as positive.
