### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by victorDaniloCasta** [sentiment-analysis-spanish/sentiment-spanish#6]
I have installed the package in a python virtualenv for use in a Django project. 

When import the main line. I get this error:

File "/home/demo/Django/project/smood/app/views.py", line 30, in <module>
    from classifier import SentimentClassifier
  File "/home/demo/Django/project/smood/env/lib/python3.8/site-packages/classifier/__init__.py", line 1, in <module>
    from .sentimentPipeline import *
  File "/home/demo/Django/project/smood/env/lib/python3.8/site-packages/classifier/sentimentPipeline.py", line 1, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/home/demo/Django/project/smood/env/lib/python3.8/site-packages/sklearn/externals/__init__.py)

I suposed the problem is for python version python3.8

**Comment by HugoJBello** [comment]
Have you tried with python 3.8?

**Comment by victorDaniloCasta** [comment]
I have write a new test into a python 3.8 virtualenv and this is the result.

![image](https://user-images.githubusercontent.com/68648695/108366131-01a53680-71c6-11eb-9177-036f4c724caa.png)

**Comment by HugoJBello** [comment]
It seems to me that the output (0.930...) is ok. 
Don't worry about the warning, it is a small issue that I have to remove.
